name: 'Print git build runner info'
description: 'Print pretty logs on repo/runner state, env vars, tags & versions. Typically executed after checkout'


inputs:
  read-package-json:
    description: 'Read generic info from the package.json file'
    required: false
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.read-package.json }}
